/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    //dependency for using json files
    implementation("com.google.code.gson:gson:2.10.1")

    implementation ("org.openjfx:javafx-controls:25.0.3")
    implementation ("org.openjfx:javafx-fxml:25.0.3")
    implementation ("org.openjfx:javafx-web:25.0.3")

}


javafx {
    version = "25.0.3"
    modules = listOf("javafx.controls", "javafx.fxml", "javafx.web")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

application {
    // Define the main class for the application.
    mainClass = "it.unicam.cs.mpgc.rpg125675.Main"
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
    jvmArgs("-Dfile.encoding=UTF-8")
}
